[files]
extend-exclude = ["ui/dev/log.jsonl","internal/tiktoken/cl100k_base.tiktoken.mbt","internal/uuid/uuid.mbt"]

[default.extend-words]
ba = "ba"
claus = "claus"
nd = "nd" 
vai = "vai"
beng = "beng"
maka = "maka"