[package]
name = "tiktoken_lexer_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
fancy-regex = "0.16.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
similar-asserts = "1.7.0"
